Update macrotest version
Emoun/duplicate pull request #21
Opened 2020-12-11 09:48 UTC by eupn

Related to https://github.com/eupn/macrotest/issues/52. The `macrotest v1.0.7` is now supporting Rust 1.34 as a MSRV, so the crate's version could be unpinned in `Cargo.toml`.

2020-12-11 12:01 UTC, Emoun requested changes
Thank you for taking the time look into my issue and committing to an MSRV. 

Before merging this PR, I'd like to wait until you have automated testing of the MSRV up and running, so the breakage doesn't accidentally happen again.

2020-12-11 12:13 UTC, Emoun approved these changes
Thanks for the changes.

2020-12-11 12:27 UTC, eupn commented
>Before merging this PR, I'd like to wait until you have automated testing of the MSRV up and running, so the breakage doesn't accidentally happen again.

Sure, I'll set up this compiler version in CI shortly.

2020-12-11 13:29 UTC, eupn commented
@Emoun got `macrotest` to compile with MSRV toolchain in CI: https://github.com/eupn/macrotest/pull/56

2020-12-13 09:02 UTC, Emoun approved these changes
@eupn thank you for taking care of it in such a timely manner. Accepting the PR.

2020-12-13 09:12 UTC, merged